services:
  master:
    image: textsearch-server:latest
    build:
      context: .
    ports:
      - "9001:9001"
      - "2552:2552"
    depends_on:
      - worker1
      - worker2
    entrypoint: sh bin/textsearch-server master

  worker1:
    image: textsearch-server:latest
    build:
      context: .
    ports:
      - "9002:9002"
      - "2553:2553"
    entrypoint: sh bin/textsearch-server worker1

  worker2:
    image: textsearch-server:latest
    build:
      context: .
    ports:
      - "9003:9003"
      - "2554:2554"
    entrypoint: sh bin/textsearch-server worker2